# Generated by Django 6.0.5 on 2026-05-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text="Short unique identifier, e.g. 'acme'", max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human name: 'Chicago Manufacturing Plant'", max_length=255)),
                ('sap_plant_code', models.CharField(blank=True, default='', help_text="WERKS value from SAP, e.g. '1000'", max_length=20)),
                ('address', models.TextField(blank=True, default='', help_text='Physical address, used to match utility service addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
                'unique_together': {('company', 'sap_plant_code')},
            },
        ),
    ]
