# Generated by Django 6.0.5 on 2026-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='error_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
