# Generated by Django 6.0.5 on 2026-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSource', '0002_add_error_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
