# Generated by Django 6.0.5 on 2026-05-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditLog', '0001_initial'),
        ('emissionRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissionRecord.emissionrecord'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['record', 'timestamp'], name='auditLog_au_record__4e057a_idx'),
        ),
    ]
