# Generated by Django 6.0.5 on 2026-05-24 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('dataSource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.IntegerField(help_text='1-indexed row number in the uploaded CSV')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Indirect (Purchased Energy)'), ('SCOPE_3', 'Scope 3 - Other Indirect')], max_length=10)),
                ('scope_3_category', models.IntegerField(blank=True, help_text='GHG Protocol Scope 3 category number (e.g. 6=Business Travel)', null=True)),
                ('activity_type', models.CharField(help_text='Canonical activity: diesel_combustion, electricity_grid, flight_economy, hotel_stay', max_length=100)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('normalized_unit', models.CharField(help_text='Canonical unit: kg, L, kWh, km, room_night', max_length=50)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('emission_factor_source', models.CharField(blank=True, default='', help_text="Reference: 'EPA 2024 Table 1', 'DEFRA 2024'", max_length=200)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated emissions in kg CO2e', max_digits=14, null=True)),
                ('activity_start_date', models.DateField()),
                ('activity_end_date', models.DateField(blank=True, help_text='Billing period end for utilities; null for point-in-time activities', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged - Suspicious'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('flag_reasons', models.JSONField(blank=True, default=list, help_text='List of reasons: ["estimated_read", "quantity_outlier"]')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Complete original CSV row as a dict')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='company.company')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='company.facility')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dataSource.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='emissionRec_company_af49fb_idx'), models.Index(fields=['company', 'scope'], name='emissionRec_company_784fb2_idx'), models.Index(fields=['source'], name='emissionRec_source__d400c4_idx'), models.Index(fields=['activity_start_date'], name='emissionRec_activit_ecb497_idx')],
            },
        ),
    ]
